### ISSUE TITLE
MLD : Modèle Logique de Données

### ISSUE THREAD

**Issue by ALapaque** [ALapaque/My-planning#5]

**Comment by ALapaque** [comment]
UPDATING with new identifying relation and nullable relation


![MCL_18-05-2021-18h48](https://user-images.githubusercontent.com/46450511/118691856-c5f02c00-b809-11eb-8d63-97572cbb53c0.png)

**Comment by xavier-lawaree** [comment]
salut ça me semble correct faut juste faire attention au partage agenda/team/user point de vue FK nullable!

**Comment by ALapaque** [comment]
@xavier-lawaree Ouaip, c'est ce que j'ai dit lors de ma réunion TFE hier.

**Comment by ALapaque** [comment]
SCRIPT TO GENERATE THE DB


-- MySQL Script generated by MySQL Workbench
-- Sun Jul 11 16:38:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idRoles_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(100) NULL,
  `lastName` VARCHAR(100) NULL,
  `username` VARCHAR(100) NULL,
  `password` VARCHAR(255) NULL,
  `email` VARCHAR(100) NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`id`, `role`),
  UNIQUE INDEX `id Users_UNIQUE` (`id` ASC),
  INDEX `fk_Users_Roles1_idx` (`role` ASC),
  CONSTRAINT `fk_Users_Roles1`
    FOREIGN KEY (`role`)
    REFERENCES `mydb`.`Roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Authorities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Authorities` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Authorities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idAuthority_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roles_has_Authorities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Roles_has_Authorities` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Roles_has_Authorities` (
  `role` INT NOT NULL,
  `authority` INT NOT NULL,
  PRIMARY KEY (`role`, `authority`),
  INDEX `fk_Roles_has_Authorities_Authorities1_idx` (`authority` ASC),
  INDEX `fk_Roles_has_Authorities_Roles1_idx` (`role` ASC),
  CONSTRAINT `fk_Roles_has_Authorities_Roles1`
    FOREIGN KEY (`role`)
    REFERENCES `mydb`.`Roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Roles_has_Authorities_Authorities1`
    FOREIGN KEY (`authority`)
    REFERENCES `mydb`.`Authorities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Teams` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Agendas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Agendas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `user` INT NULL,
  `team` INT NULL,
  PRIMARY KEY (`id`, `user`, `team`),
  INDEX `fk_Agendas_Users1_idx` (`user` ASC),
  INDEX `fk_Agendas_Teams1_idx` (`team` ASC),
  CONSTRAINT `fk_Agendas_Users1`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agendas_Teams1`
    FOREIGN KEY (`team`)
    REFERENCES `mydb`.`Teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Schedules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Schedules` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Schedules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `day` INT NOT NULL DEFAULT 0,
  `startHour` TIME NOT NULL DEFAULT '08:00',
  `endHour` TIME NOT NULL DEFAULT '17:00',
  `hasBreak` TINYINT NOT NULL DEFAULT 0,
  `startBreak` TIME NULL,
  `endBreak` TIME NULL,
  `agenda` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `agenda`),
  INDEX `fk_Schedules_Agendas1_idx` (`agenda` ASC),
  CONSTRAINT `fk_Schedules_Agendas1`
    FOREIGN KEY (`agenda`)
    REFERENCES `mydb`.`Agendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Events` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `isADayOff` TINYINT NOT NULL DEFAULT 0,
  `isPrivate` TINYINT NOT NULL DEFAULT 0,
  `statusDisplayed` VARCHAR(45) NULL COMMENT 'Enumération :\n- Disponnible\n- En déplacement\n- Provisoire\n- Absent',
  `eventType` VARCHAR(50) NULL,
  `startDate` DATETIME NULL,
  `endDate` DATETIME NULL,
  `meetingUrl` VARCHAR(255) NULL,
  `report` VARCHAR(255) NULL,
  `agenda` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `agenda`),
  INDEX `fk_Events_Agendas1_idx` (`agenda` ASC),
  CONSTRAINT `fk_Events_Agendas1`
    FOREIGN KEY (`agenda`)
    REFERENCES `mydb`.`Agendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agendas_has_Shared_Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Agendas_has_Shared_Events` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Agendas_has_Shared_Events` (
  `agenda` INT UNSIGNED NULL,
  `event` INT NULL,
  `right` VARCHAR(45) NOT NULL DEFAULT 'READ',
  PRIMARY KEY (`agenda`, `event`),
  INDEX `fk_Agendas_has_Events_Events1_idx` (`event` ASC),
  INDEX `fk_Agendas_has_Events_Agendas1_idx` (`agenda` ASC),
  CONSTRAINT `fk_Agendas_has_Events_Agendas1`
    FOREIGN KEY (`agenda`)
    REFERENCES `mydb`.`Agendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agendas_has_Events_Events1`
    FOREIGN KEY (`event`)
    REFERENCES `mydb`.`Events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tasks` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tasks` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`id`, `user`),
  INDEX `fk_Tasks_Users1_idx` (`user` ASC),
  CONSTRAINT `fk_Tasks_Users1`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comments` (
  `id` INT NOT NULL,
  `content` NVARCHAR(255) NULL,
  `event` INT NULL,
  `user` INT NOT NULL,
  `task` INT NOT NULL,
  PRIMARY KEY (`id`, `event`, `user`, `task`),
  INDEX `fk_Comments_Events1_idx` (`event` ASC),
  INDEX `fk_Comments_Users1_idx` (`user` ASC),
  INDEX `fk_Comments_Tasks1_idx` (`task` ASC),
  CONSTRAINT `fk_Comments_Events1`
    FOREIGN KEY (`event`)
    REFERENCES `mydb`.`Events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_Users1`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_Tasks1`
    FOREIGN KEY (`task`)
    REFERENCES `mydb`.`Tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users_has_Team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users_has_Team` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users_has_Team` (
  `user` INT NULL,
  `team` INT NOT NULL,
  PRIMARY KEY (`user`, `team`),
  INDEX `fk_Users_has_Team_Team1_idx` (`team` ASC),
  INDEX `fk_Users_has_Team_Users1_idx` (`user` ASC),
  CONSTRAINT `fk_Users_has_Team_Users1`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Team_Team1`
    FOREIGN KEY (`team`)
    REFERENCES `mydb`.`Teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cards` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cards` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users_has_Cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users_has_Cards` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users_has_Cards` (
  `user` INT NOT NULL,
  `card` INT NOT NULL,
  `cardName` VARCHAR(255) NULL,
  PRIMARY KEY (`user`, `card`),
  INDEX `fk_Users_has_Cards_Cards1_idx` (`card` ASC),
  INDEX `fk_Users_has_Cards_Users1_idx` (`user` ASC),
  CONSTRAINT `fk_Users_has_Cards_Users1`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Cards_Cards1`
    FOREIGN KEY (`card`)
    REFERENCES `mydb`.`Cards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teams_or_Users_has_shared_Agendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Teams_or_Users_has_shared_Agendas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Teams_or_Users_has_shared_Agendas` (
  `team` INT NULL,
  `agenda` INT UNSIGNED NULL,
  `user` INT NULL,
  PRIMARY KEY (`team`, `agenda`, `user`),
  INDEX `fk_Teams_has_Agendas_Agendas1_idx` (`agenda` ASC),
  INDEX `fk_Teams_has_Agendas_Teams1_idx` (`team` ASC),
  INDEX `fk_Teams_has_shared_Agendas_Users1_idx` (`user` ASC),
  CONSTRAINT `fk_Teams_has_Agendas_Teams1`
    FOREIGN KEY (`team`)
    REFERENCES `mydb`.`Teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teams_has_Agendas_Agendas1`
    FOREIGN KEY (`agenda`)
    REFERENCES `mydb`.`Agendas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teams_has_shared_Agendas_Users1`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

**Comment by ALapaque** [comment]
![image](https://user-images.githubusercontent.com/46450511/137628479-fec8cf26-e427-4eb9-bf29-0cfc9951c347.png)
